export const REQUEST_ERROR = 'REQUEST_ERROR';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';

export const SET_USER_REQUEST = 'SET_USER_REQUEST';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';

export const SIGNIN_WITH_GOOGLE_REQUEST = 'SIGNIN_WITH_GOOGLE_REQUEST';

export const EMAIL_VERIFICATION_REQUEST = 'EMAIL_VERIFICATION_REQUEST';

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS';

export const URL_REQUEST = 'URL_REQUEST';
export const SET_URLS = 'SET_URLS';

export const SET_ACTIVE_IMAGE = 'SET_ACTIVE_IMAGE';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const UNFAVOUR_REQUEST = 'UNFAVOUR_REQUEST';
export const SET_FAVOURITE_STATUS = 'SET_FAVOURITE_STATUS';
export const FAVOURITE_STATUS_REQUEST = 'FAVOURITE_STATUS_REQUEST';